stages:
- stage: Build
  displayName: Build and push stage
  variables:
    vmImageName: ubuntu-latest
    tag: 38
  jobs:  
  - job: Build
    displayName: Build job
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: 'codewithme/products-store-mvc'
        dockerfile: 'app/Dockerfile'
        containerRegistry: DockerHub
        tags: |
          $(tag)