# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  vmImage: ubuntu-latest

variables:
  containerRegistryServiceConnection: DockerHub
  imageName: 'codewithme/products-store-mvc'
  dockerHub: 'docker.io/codewithme/'
  tag: 38

steps:
- task: Docker@2
  displayName: 'Build Docker image'
  inputs:
    repository: $(imageName)
    containerRegistry: $(containerRegistryServiceConnection)
    command: build
    Dockerfile: app/Dockerfile
    tags: |
      $(tag)

- task: Docker@2
  displayName: Push image
  inputs:
    containerRegistry: $(containerRegistryServiceConnection)
    repository: $(imageName)
    command: push
    tags: |
      $(tag)